### ISSUE TITLE
example demo error

### ISSUE THREAD

**Issue by wuyuancai** [pinkfish/flutter_rtmppublisher#17]
I/Stuff   ( 5434): {filePath=null, bitrate=1228800, textureId=0, enableAndroidOpenGL=false, url=rtmp://34.70.40.166:1935/LiveApp/815794454132232781694481}
E/MethodChannel#plugins.flutter.io/camera_with_rtmp( 5434): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera_with_rtmp( 5434): kotlin.KotlinNullPointerException
E/MethodChannel#plugins.flutter.io/camera_with_rtmp( 5434): 	at com.whelksoft.camera_with_rtmp.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.kt:93)
E/MethodChannel#plugins.flutter.io/camera_with_rtmp( 5434): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#plugins.flutter.io/camera_with_rtmp( 5434): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/camera_with_rtmp( 5434): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#plugins.flutter.io/camera_with_rtmp( 5434): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/camera_with_rtmp( 5434): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#plugins.flutter.io/camera_with_rtmp( 5434): 	at android.os.Looper.loop(Looper.java:176)
E/MethodChannel#plugins.flutter.io/camera_with_rtmp( 5434): 	at android.app.ActivityThread.main(ActivityThread.java:7464)
E/MethodChannel#plugins.flutter.io/camera_with_rtmp( 5434): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera_with_rtmp( 5434): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
E/MethodChannel#plugins.flutter.io/camera_with_rtmp( 5434): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
I/flutter ( 5434): Error: error
I/flutter ( 5434): Error Message: null

**Comment by pinkfish** [comment]
Which method call was this?  I think I finally got the android camera2 apis to work, they are annoyingly hard to work with.

**Comment by pinkfish** [comment]
Fixed the pause methods if that was the error you ran into?

**Comment by wuyuancai** [comment]
> Which method call was this? I think I finally got the android camera2 apis to work, they are annoyingly hard to work with.

No detailed display, this error occurs when running the example. 
Locate the code location is below:
camera!!.startVideoRecordingAndStreaming(
                        call.argument("filePath")!!,
                        call.argument("url"),
                        bitrate,
                        enableOpenGL,
                        result)
