### ISSUE TITLE
Error loops infinitely when a wrong rtmp link is passed

### ISSUE THREAD

**Issue by aryanA101a** [pinkfish/flutter_rtmppublisher#66]
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: CameraException(No camera is streaming images, stopImageStream was called when no camera is streaming images.)     
E/flutter (32714): #0      CameraController.getStreamStatistics (package:degpeg/camera.dart:555)    
E/flutter (32714): #1      _LivePreviewState.startVideoStreaming.<anonymous closure> (package:degpeg_app/Screens/live_preview.dart:968)
E/flutter (32714): #2      _LivePreviewState.startVideoStreaming.<anonymous closure> (package:degpeg_app/Screens/live_preview.dart:967)
E/flutter (32714): #3      _rootRunUnary (dart:async/zone.dart:1362)
E/flutter (32714): #4      _CustomZone.runUnary (dart:async/zone.dart:1265)
E/flutter (32714): #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170)
E/flutter (32714): #6      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1207)
E/flutter (32714): #7      _rootRunUnary (dart:async/zone.dart:1370)
E/flutter (32714): #8      _CustomZone.runUnary (dart:async/zone.dart:1265)
E/flutter (32714): #9      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1191)
E/flutter (32714): #10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395)
E/flutter (32714): #11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426)
E/flutter (32714): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

**Comment by gibsmon** [comment]
check your permission android
